### ISSUE TITLE
Makefile fails

### ISSUE THREAD

**Issue by Luiz22-br** [DanielSant0s/Enceladus#11]
when i put
 make main.lua
or
 make all
it shows 
 Makefile:261: /samples/Makefile.eeglobal: Arquivo ou diretório inexistente
 make: *** Sem regra para processar o alvo '/samples/Makefile.eeglobal'.  Pare.

**Comment by israpps** [comment]
> when i put make main.lua or make all it shows Makefile:261: /samples/Makefile.eeglobal: Arquivo ou diretório inexistente make: *** Sem regra para processar o alvo '/samples/Makefile.eeglobal'. Pare.

you dont have PS2SDK properly installed it seems
