### ISSUE TITLE
file io

### ISSUE THREAD

**Issue by rodrigo1593** [DanielSant0s/Enceladus#12]
1.open file
2.write file, string example:"hello",set size of bytes/characters
3. close file
4. -----------
5. reopen file
6. rewrite file, string example:"a", set size of bytes/characters
7. close file

the output is: "aello"
like it writes on top of the same content of the file.
idk why exactly, there is a way to bypass it????

**Comment by israpps** [comment]
> 1.open file 2.write file, string example:"hello",set size of bytes/characters 3. close file 4. ----------- 5. reopen file 6. rewrite file, string example:"a", set size of bytes/characters 7. close file
> 
> the output is: "aello" like it writes on top of the same content of the file. idk why exactly, there is a way to bypass it????

use the different open mode constants to change how data is written
