### ISSUE TITLE
ADPCM Sound files

### ISSUE THREAD

**Issue by rodrigo1593** [DanielSant0s/Enceladus#17]
how the hell is the structure to play that audio file?
im sure im dumb. :c

**Comment by Wellinator** [comment]
I think you can use these methods:
https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26

**Comment by wolfysdl** [comment]
> I think you can use these methods:
> 
> https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26

It most likely a c function than a lua function

**Comment by israpps** [comment]
> > I think you can use these methods:
> > https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26
> 
> It most likely a c function than a lua function

on enceladus sound is inited by default
so you just have to setup the channels, volume and play audios

**Comment by wolfysdl** [comment]
> > > I think you can use these methods:
> > > https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26
> > 
> > 
> > It most likely a c function than a lua function
> 
> on enceladus sound is inited by default so you just have to setup the channels, volume then load & play audios from lua

That´s why i questioned this because normally this function should be a `const char*` instead of `luaState *"

**Comment by israpps** [comment]
> > > > I think you can use these methods:
> > > > https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26
> > > 
> > > 
> > > It most likely a c function than a lua function
> > 
> > 
> > on enceladus sound is inited by default so you just have to setup the channels, volume then load & play audios from lua
> 
> That´s why i questioned this because normally this function should be a `const char*` instead of `luaState *"

Don't worry of the argument of that function

The true arguments comming from the Lua script are retrieved via functions

Take a look at `Luasystem.cpp`

**Comment by wolfysdl** [comment]
> > > > > I think you can use these methods:
> > > > > https://github.com/DanielSant0s/Enceladus/blob/a37d3ec4a32c585dc8d94ad80de97ea36489a17e/src/luasound.cpp#L26
> > > > 
> > > > 
> > > > It most likely a c function than a lua function
> > > 
> > > 
> > > on enceladus sound is inited by default so you just have to setup the channels, volume then load & play audios from lua
> > 
> > 
> > That´s why i questioned this because normally this function should be a `const char*` instead of `luaState *"
> 
> Don't worry of the argument of that function
> 
> The true arguments comming from the Lua script are retrieved via functions
> 
> Take a look at `Luasystem.cpp`

Thanks for the info.

**Comment by rodrigo1593** [comment]
amazing, thought i will never an answer lmao.
i love you two!!
