### ISSUE TITLE
when keyboard & mouse support?

### ISSUE THREAD

**Issue by rodrigo1593** [DanielSant0s/Enceladus#20]
i know its hard but its possible?

**Comment by israpps** [comment]
> i know its hard but its possible?

Can be done.

IRX modules for both things already exist.

However, AFAIK only the keyboard one will function well...

Only thing that remains is adding it into Enceladus Lua

**Comment by rodrigo1593** [comment]
> > i know its hard but its possible?
> 
> Can be done.
> 
> IRX modules for both things already exist.
> 
> However, AFAIK only the keyboard one will function well...
> 
> Only thing that remains is adding it into Enceladus Lua

and how can i do that? can you teach me?/ can you add it?
