### ISSUE TITLE
Como usar o Enceladus

### ISSUE THREAD

**Issue by ATSxp** [DanielSant0s/Enceladus#7]
Olá, eu queria saber qual arquivo eu instalo e como eu começo à usa-lo, pois não tenho ideia por onde começar =)

**Comment by DanielSant0s** [comment]
Baixe o pacote compilado no link: https://github.com/DanielSant0s/Enceladus/releases/tag/latest

Já vem um com um script de exemplo então recomendo usá-lo como parâmetro de teste.
O primeiro script carregado é System/system.lua.

Caso vá usar no emulador existem instruções de utilização no readme.

**Comment by wolfysdl** [comment]
> Olá, eu queria saber qual arquivo eu instalo e como eu começo à usa-lo, pois não tenho ideia por onde começar 

Usa o makefile para instalar e depois você começa a usar a linguagem lua para scriting, caso vc queira saber dos detalhes tem as lives do daniel usando o enceladus para criar apps ou jogos

**Comment by ATSxp** [comment]
Muito obrigado ae, qualquer coisa venho pedir ajuda a você

**Comment by ATSxp** [comment]
Opa, eu de novo, eu li o Readme, ele diz que preciso usar a versão 1.7.0 do PCSX2 mas só encontro a 1.6.0 no site oficial deles, realmente preciso da versão 1.7.0?

**Comment by DanielSant0s** [comment]
Link para as versões mais recentes do PCSX2, o site deles só mostra o download de releases "totalmente estáveis": https://pcsx2.github.io/downloads.html

Aí você pode baixar a versão mais recente do PCSX2 para o seu OS

**Comment by ATSxp** [comment]
Valeu, cara.. cê não sabe o quanto sonhei em usar sua homebrew, estou muito orgulhoso de um brasileiro estar tomando a frente nisso =)

**Comment by ATSxp** [comment]
Vish, mais uma pergunta, tenho duas opçoes de downloads, uma é AVX2 e a outra é SSE4, qual a diferença delas?

**Comment by DanielSant0s** [comment]
Depende do tipo de tecnologia do teu processador, na dúvida baixa as duas e testa kkkkkkk

**Comment by ATSxp** [comment]
Sksks,  valeu ae

**Comment by ATSxp** [comment]
rapaz... as duas opçoes falharam, é , não vai ser hoje ;_;

**Comment by ATSxp** [comment]
o que aconteceria seu eu usasse uma versão mais antiga?

**Comment by terremoth** [comment]
@DanielSant0s acredito que seria legal se fizesses um tutorial, em video rapidinho, e em texto, mostrando de pegar DO ZERO até um hello world.

Imagina se esse cara aí teve esse problema, é provável que muitos outros já tiveram, a diferença é que ele veio reportar e pedir ajuda.
